[package]
name = "burn-train"
version = "0.8.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "Training crate for burn"
repository = "https://github.com/burn-rs/burn/tree/main/burn-train"

readme = "README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
burn-core = { path = "../burn-core", version = "0.8.0" }

# Console
indicatif = "0.17.2"
log4rs = { workspace = true }
log = { workspace = true }

# Metrics
nvml-wrapper = "0.8.0"
textplots = "0.8.0"
rgb = "0.8.34"
terminal_size = "0.2.3"

# Utilities
derive-new = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }

[dev-dependencies]
burn-ndarray = { path ="../burn-ndarray", version = "0.8.0" }
