[workspace]
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
  "burn",
  "burn-autodiff",
  "burn-common",
  "burn-core",
  "burn-dataset",
  "burn-derive",
  "burn-import",
  "burn-ndarray",
  "burn-no-std-tests",
  "burn-tch",
  "burn-tensor-testgen",
  "burn-tensor",
  "burn-train",
  "examples/*",
]

[workspace.dependencies]
bytemuck = "1.13"
const-random = "0.1.15"
dashmap = "5.4.0"
dirs = "5.0.0"
fake = "2.5.0"
flate2 = "1.0.26"
hashbrown = "0.13.2"
indicatif = "0.17.3"
libm = "0.2.6"
log = "0.4.17"
log4rs = "1.2.0"
pretty_assertions = "1.3"
proc-macro2 = "1.0.56"
protobuf-codegen = "3.2"
quote = "1.0.26"
rstest = "0.17.0"
spin = {version = "0.9.8", features = ["mutex", "spin_mutex"]}
strum = "0.24"
strum_macros = "0.24"
syn = "2.0"
thiserror = "1.0.40"
topological-sort = "0.2.2"

#
# The following packages disable the "std" feature for no_std compatibility
#
bincode = {version = "2.0.0-rc", features = ["alloc", "serde"], default-features = false}
derive-new = {version = "0.5.9", default-features = false}
half = {version = "2", features = ["alloc", "num-traits"], default-features = false}
ndarray = {version = "0.15.6", default-features = false}
num-traits = {version = "0.2.15", default-features = false, features = ["libm"]}# libm is for no_std
rand = {version = "0.8.5", default-features = false, features = ["std_rng"]}# std_rng is for no_std 
rand_distr = {version = "0.4.3", default-features = false}
rmp-serde = {version = "1.1.1"}
serde = {version = "1.0.160", default-features = false, features = ["derive", "alloc"]}# alloc is for no_std, derive is needed
serde_json = {version = "1.0.96", default-features = false}
uuid = {version = "1.3.2", default-features = false}
